const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_REGISTER_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_REGISTER_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILED: "FETCH_TOP_DOCTOR_FAILED",

  FETCH_TOP_SPECIALTY_SUCCESS: "FETCH_TOP_SPECIALTY_SUCCESS",
  FETCH_TOP_SPECIALTY_FAILED: "FETCH_TOP_SPECIALTY_FAILED",

  FETCH_TOP_CLINIC_SUCCESS: "FETCH_TOP_CLINIC_SUCCESS",
  FETCH_TOP_CLINIC_FAILED: "FETCH_TOP_CLINIC_FAILED",

  FETCH_HANDBOOK_SUCCESS: "FETCH_HANDBOOK_SUCCESS",
  FETCH_HANDBOOK_FAILED: "FETCH_HANDBOOK_FAILED",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILED: "FETCH_ALL_DOCTOR_FAILED",

  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAILED: "SAVE_DETAIL_DOCTOR_FAILED",

  FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: "FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_TIME_FAILED: "FETCH_ALLCODE_SCHEDULE_TIME_FAILED",

  GET_REQUIRED_DOCTOR_SUCCESS: "GET_REQUIRED_DOCTOR_SUCCESS",
  GET_REQUIRED_DOCTOR_FAILED: "GET_REQUIRED_DOCTOR_FAILED",
  GET_REQUIRED_DOCTOR_START: "GET_REQUIRED_DOCTOR_START",

  GET_LIST_CLINIC_SUCCESS: "GET_LIST_CLINIC_SUCCESS",
  GET_LIST_CLINIC_FAILED: "GET_LIST_CLINIC_FAILED",

  SOCKET_CONNECT_SUCCESS: "SOCKET_CONNECT_SUCCESS",
  SOCKET_CONNECT_FAIL: "SOCKET_CONNECT_FAIL",

  PEER_CONNECT_SUCCESS: "PEER_CONNECT_SUCCESS",
  PEER_CONNECT_FAIL: "PEER_CONNECT_FAIL",
});

export default actionTypes;
